get http://localhost:3000

# ###
# get http://localhost:3000/portfolio
# Content-Type : application/json

###
get http://localhost:3000/portfolio/presentation
Content-Type : application/json

###
get http://localhost:3000/portfolio/projets
Content-Type : application/json

###
get http://localhost:3000/portfolio/projets/projet1
Content-Type : application/json

###
get http://localhost:3000/portfolio/contact
Content-Type : application/json

###
get http://localhost:3000/portfolio/connexion
Content-Type : application/json

###
get http://localhost:3000/admin
Content-Type : application/json

###
get http://localhost:3000/admin/projet/:id
Content-Type : application/json

###
get http://localhost:3000/admin/analyses
Content-Type : application/json

###
POST http://localhost:3000/admin/projet
Content-Type : application/json

{
    "id":"1",
    "titre": "titre",
    "descriptionIntro": "texte",
    "descriptionComplete": "texte",
    "motsCles": "[mots cles]",
    "imageTh": "image",
    "images": "[images]",
    "date": "date"
}

###
DELETE http://localhost:3000/admin/projet/Projet221
Content-Type : application/json

{
    "descriptionIntro": "texte",
    "descriptionComplete": "texte",
    "motsCles": "[mots cles]",
    "imageThumbnail": "image",
    "images": "[images]",
    "date": "date"
}

###
POST http://localhost:3000/admin/connexion
Content-Type : application/json

{
    "id": "admin",
    "mdp": "adminadmin"
}